// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserFieldNames          = builder.RawFieldNames(&AeUser{}, true)
	aeUserRows                = strings.Join(aeUserFieldNames, ",")
	aeUserRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeUserRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserFieldNames, "user_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeUserModel interface {
		Insert(ctx context.Context, data *AeUser) (sql.Result, error)
		FindOne(ctx context.Context, userId string) (*AeUser, error)
		FindOneByPhone(ctx context.Context, phone string) (*AeUser, error)
		FindOneByUsername(ctx context.Context, username string) (*AeUser, error)
		Update(ctx context.Context, data *AeUser) error
		Delete(ctx context.Context, userId string) error
	}

	defaultAeUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUser struct {
		Id           int64     `db:"id"`            // 自增ID
		UserId       string    `db:"user_id"`       // 唯一标识
		Username     string    `db:"username"`      // 用户名
		PasswordHash string    `db:"password_hash"` // 用户密码
		Phone        string    `db:"phone"`         // 手机号码
		Email        string    `db:"email"`         // 邮箱地址
		AvatarUrl    string    `db:"avatar_url"`    // 用户头像URL
		Status       string    `db:"status"`        // 账号状态：active-正常, inactive-未激活
		LastLoginAt  time.Time `db:"last_login_at"` // 最后登录时间
		CreateTime   time.Time `db:"create_time"`   // 创建时间
		UpdateTime   time.Time `db:"update_time"`   // 更新时间
	}
)

func newAeUserModel(conn sqlx.SqlConn) *defaultAeUserModel {
	return &defaultAeUserModel{
		conn:  conn,
		table: `"public"."ae_user"`,
	}
}

func (m *defaultAeUserModel) Delete(ctx context.Context, userId string) error {
	query := fmt.Sprintf("delete from %s where user_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultAeUserModel) FindOne(ctx context.Context, userId string) (*AeUser, error) {
	query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", aeUserRows, m.table)
	var resp AeUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserModel) FindOneByPhone(ctx context.Context, phone string) (*AeUser, error) {
	var resp AeUser
	query := fmt.Sprintf("select %s from %s where phone = $1 limit 1", aeUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phone)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserModel) FindOneByUsername(ctx context.Context, username string) (*AeUser, error) {
	var resp AeUser
	query := fmt.Sprintf("select %s from %s where username = $1 limit 1", aeUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserModel) Insert(ctx context.Context, data *AeUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, aeUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Username, data.PasswordHash, data.Phone, data.Email, data.AvatarUrl, data.Status, data.LastLoginAt)
	return ret, err
}

func (m *defaultAeUserModel) Update(ctx context.Context, newData *AeUser) error {
	query := fmt.Sprintf("update %s set %s where user_id = $1", m.table, aeUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Id, newData.Username, newData.PasswordHash, newData.Phone, newData.Email, newData.AvatarUrl, newData.Status, newData.LastLoginAt)
	return err
}

func (m *defaultAeUserModel) tableName() string {
	return m.table
}
