// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserKeysFieldNames          = builder.RawFieldNames(&AeUserKeys{}, true)
	aeUserKeysRows                = strings.Join(aeUserKeysFieldNames, ",")
	aeUserKeysRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserKeysFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeUserKeysRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserKeysFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeUserKeysModel interface {
		Insert(ctx context.Context, data *AeUserKeys) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeUserKeys, error)
		FindOneByKeyValue(ctx context.Context, keyValue string) (*AeUserKeys, error)
		Update(ctx context.Context, data *AeUserKeys) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeUserKeysModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUserKeys struct {
		Id          int64     `db:"id"`           // 自增id,主键
		UserId      string    `db:"user_id"`      // 用户id
		KeyName     string    `db:"key_name"`     // 密钥名称
		KeyValue    string    `db:"key_value"`    // 密钥值，全局唯一
		KeyType     string    `db:"key_type"`     // 密钥类型：api-API密钥, access_token-访问令牌, refresh_token-刷新令牌, secret-密钥
		Status      string    `db:"status"`       // 密钥状态：active-有效, inactive-禁用, revoked-已撤销
		Permissions string    `db:"permissions"`  // 钥权限范围JSON数组
		ExpiresAt   time.Time `db:"expires_at"`   // 密钥过期时间
		LastUsedAt  time.Time `db:"last_used_at"` // 最后使用时间
		UsageCount  int64     `db:"usage_count"`  // 密钥使用次数统计
		CreateTime  time.Time `db:"create_time"`  // 创建时间
		UpdateTime  time.Time `db:"update_time"`  // 更新时间
	}
)

func newAeUserKeysModel(conn sqlx.SqlConn) *defaultAeUserKeysModel {
	return &defaultAeUserKeysModel{
		conn:  conn,
		table: `"public"."ae_user_keys"`,
	}
}

func (m *defaultAeUserKeysModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeUserKeysModel) FindOne(ctx context.Context, id int64) (*AeUserKeys, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeUserKeysRows, m.table)
	var resp AeUserKeys
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserKeysModel) FindOneByKeyValue(ctx context.Context, keyValue string) (*AeUserKeys, error) {
	var resp AeUserKeys
	query := fmt.Sprintf("select %s from %s where key_value = $1 limit 1", aeUserKeysRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, keyValue)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserKeysModel) Insert(ctx context.Context, data *AeUserKeys) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, aeUserKeysRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.KeyName, data.KeyValue, data.KeyType, data.Status, data.Permissions, data.ExpiresAt, data.LastUsedAt, data.UsageCount)
	return ret, err
}

func (m *defaultAeUserKeysModel) Update(ctx context.Context, newData *AeUserKeys) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeUserKeysRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.KeyName, newData.KeyValue, newData.KeyType, newData.Status, newData.Permissions, newData.ExpiresAt, newData.LastUsedAt, newData.UsageCount)
	return err
}

func (m *defaultAeUserKeysModel) tableName() string {
	return m.table
}
