// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserTokensFieldNames          = builder.RawFieldNames(&AeUserTokens{}, true)
	aeUserTokensRows                = strings.Join(aeUserTokensFieldNames, ",")
	aeUserTokensRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserTokensFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeUserTokensRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserTokensFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeUserTokensModel interface {
		Insert(ctx context.Context, data *AeUserTokens) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeUserTokens, error)
		Update(ctx context.Context, data *AeUserTokens) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeUserTokensModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUserTokens struct {
		Id         int64     `db:"id"`
		UserId     string    `db:"user_id"`
		Token      string    `db:"token"`
		ExpiresAt  time.Time `db:"expires_at"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		Status     string    `db:"status"`
	}
)

func newAeUserTokensModel(conn sqlx.SqlConn) *defaultAeUserTokensModel {
	return &defaultAeUserTokensModel{
		conn:  conn,
		table: `"public"."ae_user_tokens"`,
	}
}

func (m *defaultAeUserTokensModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeUserTokensModel) FindOne(ctx context.Context, id int64) (*AeUserTokens, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeUserTokensRows, m.table)
	var resp AeUserTokens
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserTokensModel) Insert(ctx context.Context, data *AeUserTokens) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, aeUserTokensRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Token, data.ExpiresAt, data.Status)
	return ret, err
}

func (m *defaultAeUserTokensModel) Update(ctx context.Context, data *AeUserTokens) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeUserTokensRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Token, data.ExpiresAt, data.Status)
	return err
}

func (m *defaultAeUserTokensModel) tableName() string {
	return m.table
}
