// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserBalanceStatisticDailyFieldNames          = builder.RawFieldNames(&AeUserBalanceStatisticDaily{}, true)
	aeUserBalanceStatisticDailyRows                = strings.Join(aeUserBalanceStatisticDailyFieldNames, ",")
	aeUserBalanceStatisticDailyRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserBalanceStatisticDailyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeUserBalanceStatisticDailyRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserBalanceStatisticDailyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeUserBalanceStatisticDailyModel interface {
		Insert(ctx context.Context, data *AeUserBalanceStatisticDaily) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeUserBalanceStatisticDaily, error)
		FindOneByDayUserId(ctx context.Context, day time.Time, userId string) (*AeUserBalanceStatisticDaily, error)
		Update(ctx context.Context, data *AeUserBalanceStatisticDaily) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeUserBalanceStatisticDailyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUserBalanceStatisticDaily struct {
		Id         int64     `db:"id"`          // 用户账户表
		UserId     string    `db:"user_id"`     // 用户ID
		Day        time.Time `db:"day"`         // 日期
		Balance    float64   `db:"balance"`     // 余额
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newAeUserBalanceStatisticDailyModel(conn sqlx.SqlConn) *defaultAeUserBalanceStatisticDailyModel {
	return &defaultAeUserBalanceStatisticDailyModel{
		conn:  conn,
		table: `"public"."ae_user_balance_statistic_daily"`,
	}
}

func (m *defaultAeUserBalanceStatisticDailyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeUserBalanceStatisticDailyModel) FindOne(ctx context.Context, id int64) (*AeUserBalanceStatisticDaily, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeUserBalanceStatisticDailyRows, m.table)
	var resp AeUserBalanceStatisticDaily
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserBalanceStatisticDailyModel) FindOneByDayUserId(ctx context.Context, day time.Time, userId string) (*AeUserBalanceStatisticDaily, error) {
	var resp AeUserBalanceStatisticDaily
	query := fmt.Sprintf("select %s from %s where day = $1 and user_id = $2 limit 1", aeUserBalanceStatisticDailyRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, day, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserBalanceStatisticDailyModel) Insert(ctx context.Context, data *AeUserBalanceStatisticDaily) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, aeUserBalanceStatisticDailyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Day, data.Balance)
	return ret, err
}

func (m *defaultAeUserBalanceStatisticDailyModel) Update(ctx context.Context, newData *AeUserBalanceStatisticDaily) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeUserBalanceStatisticDailyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Day, newData.Balance)
	return err
}

func (m *defaultAeUserBalanceStatisticDailyModel) tableName() string {
	return m.table
}
