// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package mcp

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpServicesStatisticToolsFieldNames          = builder.RawFieldNames(&AeMcpServicesStatisticTools{}, true)
	aeMcpServicesStatisticToolsRows                = strings.Join(aeMcpServicesStatisticToolsFieldNames, ",")
	aeMcpServicesStatisticToolsRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpServicesStatisticToolsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpServicesStatisticToolsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpServicesStatisticToolsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpServicesStatisticToolsModel interface {
		Insert(ctx context.Context, data *AeMcpServicesStatisticTools) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpServicesStatisticTools, error)
		FindOneByYearMonthDayHourToolName(ctx context.Context, year int64, month int64, day int64, hour int64, toolName string) (*AeMcpServicesStatisticTools, error)
		Update(ctx context.Context, data *AeMcpServicesStatisticTools) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpServicesStatisticToolsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpServicesStatisticTools struct {
		Id           int64     `db:"id"`            // 自增ID
		ServerId     string    `db:"server_id"`     // 服务ID
		ToolName     string    `db:"tool_name"`     // 工具名称
		Year         int64     `db:"year"`          // 年
		Month        int64     `db:"month"`         // 月
		Day          int64     `db:"day"`           // 日
		Hour         int64     `db:"hour"`          // 小时
		ResponseTime float64   `db:"response_time"` // 小时平均响应时间(毫秒)
		RequestTotal int64     `db:"request_total"` // 小时内请求次数
		CreateTime   time.Time `db:"create_time"`   // 创建时间
	}
)

func newAeMcpServicesStatisticToolsModel(conn sqlx.SqlConn) *defaultAeMcpServicesStatisticToolsModel {
	return &defaultAeMcpServicesStatisticToolsModel{
		conn:  conn,
		table: `"public"."ae_mcp_services_statistic_tools"`,
	}
}

func (m *defaultAeMcpServicesStatisticToolsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpServicesStatisticToolsModel) FindOne(ctx context.Context, id int64) (*AeMcpServicesStatisticTools, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpServicesStatisticToolsRows, m.table)
	var resp AeMcpServicesStatisticTools
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesStatisticToolsModel) FindOneByYearMonthDayHourToolName(ctx context.Context, year int64, month int64, day int64, hour int64, toolName string) (*AeMcpServicesStatisticTools, error) {
	var resp AeMcpServicesStatisticTools
	query := fmt.Sprintf("select %s from %s where year = $1 and month = $2 and day = $3 and hour = $4 and tool_name = $5 limit 1", aeMcpServicesStatisticToolsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, year, month, day, hour, toolName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesStatisticToolsModel) Insert(ctx context.Context, data *AeMcpServicesStatisticTools) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, aeMcpServicesStatisticToolsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ServerId, data.ToolName, data.Year, data.Month, data.Day, data.Hour, data.ResponseTime, data.RequestTotal)
	return ret, err
}

func (m *defaultAeMcpServicesStatisticToolsModel) Update(ctx context.Context, newData *AeMcpServicesStatisticTools) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpServicesStatisticToolsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ServerId, newData.ToolName, newData.Year, newData.Month, newData.Day, newData.Hour, newData.ResponseTime, newData.RequestTotal)
	return err
}

func (m *defaultAeMcpServicesStatisticToolsModel) tableName() string {
	return m.table
}
