// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package mcp

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpServicesRequestLogsFieldNames          = builder.RawFieldNames(&AeMcpServicesRequestLogs{}, true)
	aeMcpServicesRequestLogsRows                = strings.Join(aeMcpServicesRequestLogsFieldNames, ",")
	aeMcpServicesRequestLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpServicesRequestLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpServicesRequestLogsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpServicesRequestLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpServicesRequestLogsModel interface {
		Insert(ctx context.Context, data *AeMcpServicesRequestLogs) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpServicesRequestLogs, error)
		Update(ctx context.Context, data *AeMcpServicesRequestLogs) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpServicesRequestLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpServicesRequestLogs struct {
		Id           int64     `db:"id"`            // 自增主键
		ServerId     string    `db:"server_id"`     // 服务ID
		ToolName     string    `db:"tool_name"`     // 工具名称
		RequestTime  time.Time `db:"request_time"`  // 请求时间
		ReturnTime   time.Time `db:"return_time"`   // 返回时间
		ResponseTime int64     `db:"response_time"` // 响应时间(毫秒)
		Status       int64     `db:"status"`        // 请求状态：-1 失败 0 位置 1 成功
		CreateTime   time.Time `db:"create_time"`   // 创建时间
		UpdateTime   time.Time `db:"update_time"`   // 更新时间
	}
)

func newAeMcpServicesRequestLogsModel(conn sqlx.SqlConn) *defaultAeMcpServicesRequestLogsModel {
	return &defaultAeMcpServicesRequestLogsModel{
		conn:  conn,
		table: `"public"."ae_mcp_services_request_logs"`,
	}
}

func (m *defaultAeMcpServicesRequestLogsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpServicesRequestLogsModel) FindOne(ctx context.Context, id int64) (*AeMcpServicesRequestLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpServicesRequestLogsRows, m.table)
	var resp AeMcpServicesRequestLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesRequestLogsModel) Insert(ctx context.Context, data *AeMcpServicesRequestLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, aeMcpServicesRequestLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ServerId, data.ToolName, data.RequestTime, data.ReturnTime, data.ResponseTime, data.Status)
	return ret, err
}

func (m *defaultAeMcpServicesRequestLogsModel) Update(ctx context.Context, data *AeMcpServicesRequestLogs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpServicesRequestLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ServerId, data.ToolName, data.RequestTime, data.ReturnTime, data.ResponseTime, data.Status)
	return err
}

func (m *defaultAeMcpServicesRequestLogsModel) tableName() string {
	return m.table
}
