// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package mcp

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpServicesStatisticFieldNames          = builder.RawFieldNames(&AeMcpServicesStatistic{}, true)
	aeMcpServicesStatisticRows                = strings.Join(aeMcpServicesStatisticFieldNames, ",")
	aeMcpServicesStatisticRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpServicesStatisticFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpServicesStatisticRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpServicesStatisticFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpServicesStatisticModel interface {
		Insert(ctx context.Context, data *AeMcpServicesStatistic) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpServicesStatistic, error)
		FindOneByYearMonthDayHour(ctx context.Context, year int64, month int64, day int64, hour int64) (*AeMcpServicesStatistic, error)
		Update(ctx context.Context, data *AeMcpServicesStatistic) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpServicesStatisticModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpServicesStatistic struct {
		Id           int64     `db:"id"`            // 自增ID
		ServerId     string    `db:"server_id"`     // 服务ID
		Year         int64     `db:"year"`          // 年
		Month        int64     `db:"month"`         // 月
		Day          int64     `db:"day"`           // 日
		Hour         int64     `db:"hour"`          // 小时
		ResponseTime int64     `db:"response_time"` // 小时平均响应时间(毫秒)
		RequestTotal int64     `db:"request_total"` // 小时内请求次数
		CreateTime   time.Time `db:"create_time"`   // 创建时间
	}
)

func newAeMcpServicesStatisticModel(conn sqlx.SqlConn) *defaultAeMcpServicesStatisticModel {
	return &defaultAeMcpServicesStatisticModel{
		conn:  conn,
		table: `"public"."ae_mcp_services_statistic"`,
	}
}

func (m *defaultAeMcpServicesStatisticModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpServicesStatisticModel) FindOne(ctx context.Context, id int64) (*AeMcpServicesStatistic, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpServicesStatisticRows, m.table)
	var resp AeMcpServicesStatistic
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesStatisticModel) FindOneByYearMonthDayHour(ctx context.Context, year int64, month int64, day int64, hour int64) (*AeMcpServicesStatistic, error) {
	var resp AeMcpServicesStatistic
	query := fmt.Sprintf("select %s from %s where year = $1 and month = $2 and day = $3 and hour = $4 limit 1", aeMcpServicesStatisticRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, year, month, day, hour)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesStatisticModel) Insert(ctx context.Context, data *AeMcpServicesStatistic) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, aeMcpServicesStatisticRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ServerId, data.Year, data.Month, data.Day, data.Hour, data.ResponseTime, data.RequestTotal)
	return ret, err
}

func (m *defaultAeMcpServicesStatisticModel) Update(ctx context.Context, newData *AeMcpServicesStatistic) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpServicesStatisticRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ServerId, newData.Year, newData.Month, newData.Day, newData.Hour, newData.ResponseTime, newData.RequestTotal)
	return err
}

func (m *defaultAeMcpServicesStatisticModel) tableName() string {
	return m.table
}
