// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package mcp

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/lib/pq"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpServicesFieldNames          = builder.RawFieldNames(&AeMcpServices{}, true)
	aeMcpServicesRows                = strings.Join(aeMcpServicesFieldNames, ",")
	aeMcpServicesRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpServicesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpServicesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpServicesFieldNames, "server_id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpServicesModel interface {
		Insert(ctx context.Context, data *AeMcpServices) (sql.Result, error)
		FindOne(ctx context.Context, serverId string) (*AeMcpServices, error)
		Update(ctx context.Context, data *AeMcpServices) error
		Delete(ctx context.Context, serverId string) error
	}

	defaultAeMcpServicesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpServices struct {
		Id              int64          `db:"id"`               // 自增ID
		ServerId        string         `db:"server_id"`        // 服务ID
		ServerName      string         `db:"server_name"`      // 服务名称
		Logo            string         `db:"logo"`             // logo
		ProtocolVersion string         `db:"protocol_version"` // 协议版本号
		Enabled         bool           `db:"enabled"`          // 是否开启
		Tags            pq.StringArray `db:"tags"`             // 标签名称（多个）
		Description     string         `db:"description"`      // 描述
		TaskChainId     int64          `db:"task_chain_id"`    // 任务链id
		CreateTime      time.Time      `db:"create_time"`      // 创建时间
		UpdateTime      time.Time      `db:"update_time"`      // 更新时间
		XNetServiceId   sql.NullString `db:"x_net_service_id"` // XNetServiceID
		CallNum         int64          `db:"call_num"`         // 调用次数
		CallSuccessNum  int64          `db:"call_success_num"` // 调用成功次数
		ResponseTime    float64        `db:"response_time"`    // 响应时间 毫秒（平均值）
		IsCreated       bool           `db:"is_created"`       // 是否启动时创建服务：true 是 false 否
		ProjectName     string         `db:"project_name"`     // 项目名称
	}
)

func newAeMcpServicesModel(conn sqlx.SqlConn) *defaultAeMcpServicesModel {
	return &defaultAeMcpServicesModel{
		conn:  conn,
		table: `"public"."ae_mcp_services"`,
	}
}

func (m *defaultAeMcpServicesModel) Delete(ctx context.Context, serverId string) error {
	query := fmt.Sprintf("delete from %s where server_id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, serverId)
	return err
}

func (m *defaultAeMcpServicesModel) FindOne(ctx context.Context, serverId string) (*AeMcpServices, error) {
	query := fmt.Sprintf("select %s from %s where server_id = $1 limit 1", aeMcpServicesRows, m.table)
	var resp AeMcpServices
	err := m.conn.QueryRowCtx(ctx, &resp, query, serverId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpServicesModel) Insert(ctx context.Context, data *AeMcpServices) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)", m.table, aeMcpServicesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ServerId, data.ServerName, data.Logo, data.ProtocolVersion, data.Enabled, data.Tags, data.Description, data.TaskChainId, data.XNetServiceId, data.CallNum, data.CallSuccessNum, data.ResponseTime, data.IsCreated, data.ProjectName)
	return ret, err
}

func (m *defaultAeMcpServicesModel) Update(ctx context.Context, data *AeMcpServices) error {
	query := fmt.Sprintf("update %s set %s where server_id = $1", m.table, aeMcpServicesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ServerId, data.Id, data.ServerName, data.Logo, data.ProtocolVersion, data.Enabled, data.Tags, data.Description, data.TaskChainId, data.XNetServiceId, data.CallNum, data.CallSuccessNum, data.ResponseTime, data.IsCreated, data.ProjectName)
	return err
}

func (m *defaultAeMcpServicesModel) tableName() string {
	return m.table
}
