// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package mcp

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpToolsFieldNames          = builder.RawFieldNames(&AeMcpTools{}, true)
	aeMcpToolsRows                = strings.Join(aeMcpToolsFieldNames, ",")
	aeMcpToolsRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpToolsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpToolsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpToolsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpToolsModel interface {
		Insert(ctx context.Context, data *AeMcpTools) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpTools, error)
		Update(ctx context.Context, data *AeMcpTools) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpToolsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpTools struct {
		Id          int64     `db:"id"`          // 主键
		ServiceId   int64     `db:"service_id"`  // 服务ID
		Name        string    `db:"name"`        // 工具名称
		Description string    `db:"description"` // 工具描述
		ArgsSchema  string    `db:"args_schema"` // 参数
		CreateTime  time.Time `db:"create_time"` // 创建时间
		UpdateTime  time.Time `db:"update_time"` // 更新时间
	}
)

func newAeMcpToolsModel(conn sqlx.SqlConn) *defaultAeMcpToolsModel {
	return &defaultAeMcpToolsModel{
		conn:  conn,
		table: `"public"."ae_mcp_tools"`,
	}
}

func (m *defaultAeMcpToolsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpToolsModel) FindOne(ctx context.Context, id int64) (*AeMcpTools, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpToolsRows, m.table)
	var resp AeMcpTools
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpToolsModel) Insert(ctx context.Context, data *AeMcpTools) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, aeMcpToolsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ServiceId, data.Name, data.Description, data.ArgsSchema)
	return ret, err
}

func (m *defaultAeMcpToolsModel) Update(ctx context.Context, data *AeMcpTools) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpToolsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.ServiceId, data.Name, data.Description, data.ArgsSchema)
	return err
}

func (m *defaultAeMcpToolsModel) tableName() string {
	return m.table
}
