// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package config

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpTaskNodeFieldNames          = builder.RawFieldNames(&AeMcpTaskNode{}, true)
	aeMcpTaskNodeRows                = strings.Join(aeMcpTaskNodeFieldNames, ",")
	aeMcpTaskNodeRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpTaskNodeFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpTaskNodeRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpTaskNodeFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpTaskNodeModel interface {
		Insert(ctx context.Context, data *AeMcpTaskNode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpTaskNode, error)
		FindOneByExternalServiceId(ctx context.Context, externalServiceId string) (*AeMcpTaskNode, error)
		Update(ctx context.Context, data *AeMcpTaskNode) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpTaskNodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpTaskNode struct {
		Id                int64     `db:"id"`                  // 自增ID
		NodeName          string    `db:"node_name"`           // 节点名称
		NodeHandle        string    `db:"node_handle"`         // 节点处理(处理函数名称)
		Enabled           bool      `db:"enabled"`             // 是否启用
		CreateTime        time.Time `db:"create_time"`         // 创建时间
		UpdateTime        time.Time `db:"update_time"`         // 更新时间
		ExternalServiceId string    `db:"external_service_id"` // 外部服务配置ID
		Description       string    `db:"description"`         // 节点描述
	}
)

func newAeMcpTaskNodeModel(conn sqlx.SqlConn) *defaultAeMcpTaskNodeModel {
	return &defaultAeMcpTaskNodeModel{
		conn:  conn,
		table: `"public"."ae_mcp_task_node"`,
	}
}

func (m *defaultAeMcpTaskNodeModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpTaskNodeModel) FindOne(ctx context.Context, id int64) (*AeMcpTaskNode, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpTaskNodeRows, m.table)
	var resp AeMcpTaskNode
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpTaskNodeModel) FindOneByExternalServiceId(ctx context.Context, externalServiceId string) (*AeMcpTaskNode, error) {
	var resp AeMcpTaskNode
	query := fmt.Sprintf("select %s from %s where external_service_id = $1 limit 1", aeMcpTaskNodeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, externalServiceId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpTaskNodeModel) Insert(ctx context.Context, data *AeMcpTaskNode) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, aeMcpTaskNodeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.NodeName, data.NodeHandle, data.Enabled, data.ExternalServiceId, data.Description)
	return ret, err
}

func (m *defaultAeMcpTaskNodeModel) Update(ctx context.Context, newData *AeMcpTaskNode) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpTaskNodeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.NodeName, newData.NodeHandle, newData.Enabled, newData.ExternalServiceId, newData.Description)
	return err
}

func (m *defaultAeMcpTaskNodeModel) tableName() string {
	return m.table
}
