// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package config

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpExternalServicesConfigFieldNames          = builder.RawFieldNames(&AeMcpExternalServicesConfig{}, true)
	aeMcpExternalServicesConfigRows                = strings.Join(aeMcpExternalServicesConfigFieldNames, ",")
	aeMcpExternalServicesConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpExternalServicesConfigFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpExternalServicesConfigRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpExternalServicesConfigFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpExternalServicesConfigModel interface {
		Insert(ctx context.Context, data *AeMcpExternalServicesConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesConfig, error)
		Update(ctx context.Context, data *AeMcpExternalServicesConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpExternalServicesConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpExternalServicesConfig struct {
		Id                int64     `db:"id"`                  // 自增id
		Name              string    `db:"name"`                // 服务名称
		Type              string    `db:"type"`                // 服务类型：stdio-标准输入输出，sse-SSE连接
		LaunchInfo        string    `db:"launch_info"`         // 启动信息，如：{  "command": "node",  "args": ["server.js"],  "workdir": "/opt/mcp/news",  "env": {"PORT": "8080"},  "max_instance":1, //最大实例数  "max_restarts":3, // 实例最大连接数  "launch_timeout":100000, //服务启动超时时间（毫秒）  "shutdown_timeout": 100000,//服务关闭时的超时时间（毫秒）  "idle_ttl": 100000000 //服务空闲存活时间（毫秒）}
		CreateTime        time.Time `db:"create_time"`         // 创建时间
		UpdateTime        time.Time `db:"update_time"`         // 更新时间
		ConnectInfo       string    `db:"connect_info"`        // 连接信息，如：{  "url": "http://api.remote.com/mcp/sse",  "headers": {"Authorization": "Bearer xxx"},  "connect_timeout": 3000,//连接超时时间（毫秒）  "max_connect":10,//实例最大连接数  "max_retry":3,//最大重试次数  "interval":1000,//重试间隔}
		ExternalServiceId string    `db:"external_service_id"` // 外部服务唯一标识
		MaxInstance       int64     `db:"max_instance"`        // 最大实例(启动几个服务实例)
		CreateStatus      bool      `db:"create_status"`       // true 已创建 false 未创建
		Description       string    `db:"description"`         // 服务描述
		ProjectName       string    `db:"project_name"`        // 项目名称
	}
)

func newAeMcpExternalServicesConfigModel(conn sqlx.SqlConn) *defaultAeMcpExternalServicesConfigModel {
	return &defaultAeMcpExternalServicesConfigModel{
		conn:  conn,
		table: `"public"."ae_mcp_external_services_config"`,
	}
}

func (m *defaultAeMcpExternalServicesConfigModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpExternalServicesConfigModel) FindOne(ctx context.Context, id int64) (*AeMcpExternalServicesConfig, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpExternalServicesConfigRows, m.table)
	var resp AeMcpExternalServicesConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpExternalServicesConfigModel) Insert(ctx context.Context, data *AeMcpExternalServicesConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, aeMcpExternalServicesConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Type, data.LaunchInfo, data.ConnectInfo, data.ExternalServiceId, data.MaxInstance, data.CreateStatus, data.Description, data.ProjectName)
	return ret, err
}

func (m *defaultAeMcpExternalServicesConfigModel) Update(ctx context.Context, data *AeMcpExternalServicesConfig) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpExternalServicesConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Type, data.LaunchInfo, data.ConnectInfo, data.ExternalServiceId, data.MaxInstance, data.CreateStatus, data.Description, data.ProjectName)
	return err
}

func (m *defaultAeMcpExternalServicesConfigModel) tableName() string {
	return m.table
}
