// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0-alpha

package config

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/lib/pq"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeMcpTaskChainFieldNames          = builder.RawFieldNames(&AeMcpTaskChain{}, true)
	aeMcpTaskChainRows                = strings.Join(aeMcpTaskChainFieldNames, ",")
	aeMcpTaskChainRowsExpectAutoSet   = strings.Join(stringx.Remove(aeMcpTaskChainFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeMcpTaskChainRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeMcpTaskChainFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeMcpTaskChainModel interface {
		Insert(ctx context.Context, data *AeMcpTaskChain) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeMcpTaskChain, error)
		Update(ctx context.Context, data *AeMcpTaskChain) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeMcpTaskChainModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeMcpTaskChain struct {
		Id         int64         `db:"id"`          // 自增ID，主键
		Name       string        `db:"name"`        // 任务链名称
		Status     string        `db:"status"`      // 任务链状态：create 创建中;used 使用中; stop 已停用;
		NodeIds    pq.Int64Array `db:"node_ids"`    // 节点ID数组
		CreateTime time.Time     `db:"create_time"` // 创建时间
		UpdateTime time.Time     `db:"update_time"` // 更新时间
	}
)

func newAeMcpTaskChainModel(conn sqlx.SqlConn) *defaultAeMcpTaskChainModel {
	return &defaultAeMcpTaskChainModel{
		conn:  conn,
		table: `"public"."ae_mcp_task_chain"`,
	}
}

func (m *defaultAeMcpTaskChainModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeMcpTaskChainModel) FindOne(ctx context.Context, id int64) (*AeMcpTaskChain, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeMcpTaskChainRows, m.table)
	var resp AeMcpTaskChain
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeMcpTaskChainModel) Insert(ctx context.Context, data *AeMcpTaskChain) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, aeMcpTaskChainRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Status, data.NodeIds)
	return ret, err
}

func (m *defaultAeMcpTaskChainModel) Update(ctx context.Context, data *AeMcpTaskChain) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeMcpTaskChainRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Status, data.NodeIds)
	return err
}

func (m *defaultAeMcpTaskChainModel) tableName() string {
	return m.table
}
