// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package fund

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeRechargeAllocationFieldNames          = builder.RawFieldNames(&AeRechargeAllocation{}, true)
	aeRechargeAllocationRows                = strings.Join(aeRechargeAllocationFieldNames, ",")
	aeRechargeAllocationRowsExpectAutoSet   = strings.Join(stringx.Remove(aeRechargeAllocationFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeRechargeAllocationRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeRechargeAllocationFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeRechargeAllocationModel interface {
		Insert(ctx context.Context, data *AeRechargeAllocation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeRechargeAllocation, error)
		FindOneByRechargeRecordIdConsumptionDailyId(ctx context.Context, rechargeRecordId int64, consumptionDailyId int64) (*AeRechargeAllocation, error)
		Update(ctx context.Context, data *AeRechargeAllocation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeRechargeAllocationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeRechargeAllocation struct {
		Id                 int64     `db:"id"`
		ConsumptionDailyId int64     `db:"consumption_daily_id"` // 关联 ae_user_consumption_record_daily 主键
		RechargeRecordId   int64     `db:"recharge_record_id"`   // 关联 ae_user_recharge_record 主键
		DeductedAmount     float64   `db:"deducted_amount"`      // 本次核销扣减的金额
		CreateTime         time.Time `db:"create_time"`          // 创建时间
		UpdateTime         time.Time `db:"update_time"`          // 更新时间
	}
)

func newAeRechargeAllocationModel(conn sqlx.SqlConn) *defaultAeRechargeAllocationModel {
	return &defaultAeRechargeAllocationModel{
		conn:  conn,
		table: `"public"."ae_recharge_allocation"`,
	}
}

func (m *defaultAeRechargeAllocationModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeRechargeAllocationModel) FindOne(ctx context.Context, id int64) (*AeRechargeAllocation, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeRechargeAllocationRows, m.table)
	var resp AeRechargeAllocation
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeRechargeAllocationModel) FindOneByRechargeRecordIdConsumptionDailyId(ctx context.Context, rechargeRecordId int64, consumptionDailyId int64) (*AeRechargeAllocation, error) {
	var resp AeRechargeAllocation
	query := fmt.Sprintf("select %s from %s where recharge_record_id = $1 and consumption_daily_id = $2 limit 1", aeRechargeAllocationRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, rechargeRecordId, consumptionDailyId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeRechargeAllocationModel) Insert(ctx context.Context, data *AeRechargeAllocation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, aeRechargeAllocationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConsumptionDailyId, data.RechargeRecordId, data.DeductedAmount)
	return ret, err
}

func (m *defaultAeRechargeAllocationModel) Update(ctx context.Context, newData *AeRechargeAllocation) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeRechargeAllocationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.ConsumptionDailyId, newData.RechargeRecordId, newData.DeductedAmount)
	return err
}

func (m *defaultAeRechargeAllocationModel) tableName() string {
	return m.table
}
