// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package fund

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserConsumptionRecordDailyFieldNames          = builder.RawFieldNames(&AeUserConsumptionRecordDaily{}, true)
	aeUserConsumptionRecordDailyRows                = strings.Join(aeUserConsumptionRecordDailyFieldNames, ",")
	aeUserConsumptionRecordDailyRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserConsumptionRecordDailyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeUserConsumptionRecordDailyRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserConsumptionRecordDailyFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeUserConsumptionRecordDailyModel interface {
		Insert(ctx context.Context, data *AeUserConsumptionRecordDaily) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeUserConsumptionRecordDaily, error)
		FindOneByDayUserId(ctx context.Context, day time.Time, userId string) (*AeUserConsumptionRecordDaily, error)
		Update(ctx context.Context, data *AeUserConsumptionRecordDaily) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeUserConsumptionRecordDailyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUserConsumptionRecordDaily struct {
		Id              int64     `db:"id"`               // 用户日消费统计表id
		UserId          string    `db:"user_id"`          // 用户uuid
		CreateTime      time.Time `db:"create_time"`      // 创建时间
		Day             time.Time `db:"day"`              // 日期
		XlcreditConsume float64   `db:"xlcredit_consume"` // 消费金额
	}
)

func newAeUserConsumptionRecordDailyModel(conn sqlx.SqlConn) *defaultAeUserConsumptionRecordDailyModel {
	return &defaultAeUserConsumptionRecordDailyModel{
		conn:  conn,
		table: `"public"."ae_user_consumption_record_daily"`,
	}
}

func (m *defaultAeUserConsumptionRecordDailyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeUserConsumptionRecordDailyModel) FindOne(ctx context.Context, id int64) (*AeUserConsumptionRecordDaily, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeUserConsumptionRecordDailyRows, m.table)
	var resp AeUserConsumptionRecordDaily
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserConsumptionRecordDailyModel) FindOneByDayUserId(ctx context.Context, day time.Time, userId string) (*AeUserConsumptionRecordDaily, error) {
	var resp AeUserConsumptionRecordDaily
	query := fmt.Sprintf("select %s from %s where day = $1 and user_id = $2 limit 1", aeUserConsumptionRecordDailyRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, day, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserConsumptionRecordDailyModel) Insert(ctx context.Context, data *AeUserConsumptionRecordDaily) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, aeUserConsumptionRecordDailyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Day, data.XlcreditConsume)
	return ret, err
}

func (m *defaultAeUserConsumptionRecordDailyModel) Update(ctx context.Context, newData *AeUserConsumptionRecordDaily) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeUserConsumptionRecordDailyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Day, newData.XlcreditConsume)
	return err
}

func (m *defaultAeUserConsumptionRecordDailyModel) tableName() string {
	return m.table
}
