// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package fund

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	aeUserRechargeRecordFieldNames          = builder.RawFieldNames(&AeUserRechargeRecord{}, true)
	aeUserRechargeRecordRows                = strings.Join(aeUserRechargeRecordFieldNames, ",")
	aeUserRechargeRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(aeUserRechargeRecordFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	aeUserRechargeRecordRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(aeUserRechargeRecordFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	aeUserRechargeRecordModel interface {
		Insert(ctx context.Context, data *AeUserRechargeRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AeUserRechargeRecord, error)
		Update(ctx context.Context, data *AeUserRechargeRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAeUserRechargeRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AeUserRechargeRecord struct {
		Id                int64          `db:"id"`              //  用户充值记录表id
		UserId            string         `db:"user_id"`         // 用户uuid
		XlcreditAmount    float64        `db:"xlcredit_amount"` // 充值金额
		PayTime           time.Time      `db:"pay_time"`        // 充值时间（支付时间）
		CreateTime        time.Time      `db:"create_time"`     // 创建时间
		UpdateTime        time.Time      `db:"update_time"`     // 更新时间
		ChargeSource      int64          `db:"charge_source"`   // 充值来源：1 ：系统赠送；2：支付宝；3：微信；4：银行卡-1：系统扣减
		ChargeType        int64          `db:"charge_type"`     // 充值类型：1 用户常规充值；2 系统故障补偿；3 活动赠送；4 过期扣减；5 管理员扣减
		Remark            sql.NullString `db:"remark"`          // 管理员充值/扣减后台备注
		Operator          sql.NullString `db:"operator"`
		ExpireTime        sql.NullTime   `db:"expire_time"`         // 过期时间（空表示永久有效）
		RelatedRechargeId sql.NullInt64  `db:"related_recharge_id"` // 负值扣减记录关联的正值记录
	}
)

func newAeUserRechargeRecordModel(conn sqlx.SqlConn) *defaultAeUserRechargeRecordModel {
	return &defaultAeUserRechargeRecordModel{
		conn:  conn,
		table: `"public"."ae_user_recharge_record"`,
	}
}

func (m *defaultAeUserRechargeRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAeUserRechargeRecordModel) FindOne(ctx context.Context, id int64) (*AeUserRechargeRecord, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", aeUserRechargeRecordRows, m.table)
	var resp AeUserRechargeRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAeUserRechargeRecordModel) Insert(ctx context.Context, data *AeUserRechargeRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, aeUserRechargeRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.XlcreditAmount, data.PayTime, data.ChargeSource, data.ChargeType, data.Remark, data.Operator, data.ExpireTime, data.RelatedRechargeId)
	return ret, err
}

func (m *defaultAeUserRechargeRecordModel) Update(ctx context.Context, data *AeUserRechargeRecord) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, aeUserRechargeRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.XlcreditAmount, data.PayTime, data.ChargeSource, data.ChargeType, data.Remark, data.Operator, data.ExpireTime, data.RelatedRechargeId)
	return err
}

func (m *defaultAeUserRechargeRecordModel) tableName() string {
	return m.table
}
